title: "Fleeting Technology"
description: "Ramblings of a mad man, spiced up with some interesting tidbits.\nIf you have found an issue or would to like to provide additions, feel free to open an issue."
author: "fleetingTech"

theme: minima

base_url: ""
repository: fleetingTech/fleetingTech.github.io



# Minima social links
github_username: fleetingTech
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/misc.md
  - _pages/theory.md
  - _pages/applied.md
  - _pages/fleeting.md
  - _pages/archive.md
  - _pages/now.md
  - _pages/about.md


include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
  
plugins:
  - jemoji
